### ISSUE TITLE
Error converting Bean with class org.grails.validation.ConstrainedDelegate

### ISSUE THREAD

**Issue by Erando89** [grails-plugins/grails-plugin-converters#12]
Hi,
I'm having a issue with Grails 3.3.9:
`compile 'org.grails.plugins:converters:3.3.1' // Provides JSON and XML converters`
In a gsp file I'd like to use `someMap as JSON`. But eventually I get this error:

```
Caused by: org.grails.web.converters.exceptions.ConverterException: Error converting Bean with class org.grails.validation.ConstrainedDelegate
	at org.grails.web.converters.marshaller.json.GroovyBeanMarshaller.marshalObject(GroovyBeanMarshaller.java:85)
	at org.grails.web.converters.marshaller.json.GroovyBeanMarshaller.marshalObject(GroovyBeanMarshaller.java:39)
	at grails.converters.JSON.value(JSON.java:184)
	at grails.converters.JSON.convertAnother(JSON.java:144)
	at org.grails.web.converters.marshaller.json.MapMarshaller.marshalObject(MapMarshaller.java:45)
	at org.grails.web.converters.marshaller.json.MapMarshaller.marshalObject(MapMarshaller.java:30)
	at grails.converters.JSON.value(JSON.java:184)
	at grails.converters.JSON.convertAnother(JSON.java:144)
	at org.grails.web.converters.marshaller.json.MapMarshaller.marshalObject(MapMarshaller.java:45)
	at org.grails.web.converters.marshaller.json.MapMarshaller.marshalObject(MapMarshaller.java:30)
	at grails.converters.JSON.value(JSON.java:184)
	at grails.converters.JSON.render(JSON.java:119)
	at org.grails.web.converters.AbstractConverter.writeTo(AbstractConverter.java:110)
	at org.grails.buffer.GrailsPrintWriter.writeWritable(GrailsPrintWriter.java:568)
	at org.grails.buffer.GrailsPrintWriter.print(GrailsPrintWriter.java:576)
	at sun.reflect.GeneratedMethodAccessor892.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:169)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at C__repo_grails_app_views_desktop__pass_model_to_js_desktop_inc_gsp.run(C__repo_grails_app_views_desktop__pass_model_to_js_desktop_inc_gsp:39)
```

What could cause that problem?

**Comment by Erando89** [comment]
I have found out that the problem only occurs when I'm trying to convert a domain class object with defined `constraints`.
